### ISSUE TITLE
Hot unplug memory

### ISSUE THREAD

**Issue by ahrechushkin** [ManageIQ/manageiq-providers-ovirt#416]
I use RHV and Ovirt (4.3+) as providers
When i try to start hot reconfiguration VM (decrease CPU and RAM)
CPU decreased after restart VM, but RAM is not decreased
In automation log i see this message.

[----] I, [2019-10-21T14:33:05.212956 #862:598f80]  INFO -- : Instance [/ManageIQ/System/Event/EmsEvent/RHEVM/NO_MEMORY_DEVICE_TO_HOT_UNPLUG] not found in MiqAeDatastore - trying [.missing]
[----] I, [2019-10-21T14:33:05.219186 #870:598f80]  INFO -- : Updated namespace [System/event_handlers/event_action_policy  ManageIQ/System]
[----] I, [2019-10-21T14:33:05.223049 #862:598f80]  INFO -- : Followed  Relationship [miqaedb:/System/Event/EmsEvent/RHEVM/NO_MEMORY_DEVICE_TO_HOT_UNPLUG#create]
And when i try use hot decrease memory from UI Ovirt/RHV - all works fine (memory decreased after restart)

Think that problem exists cause we have no exceptions on this event
https://github.com/ManageIQ/manageiq-providers-ovirt/blob/0b4b6289fad7b8e9136e054f973919da8f4769a6/app/models/manageiq/providers/redhat/infra_manager/event_fetcher.rb#L852

**Comment by ahrechushkin** [comment]
@borod108 Hello, can you check it?

**Comment by mwperina** [comment]
Roberto, could you please take a look?
@gekorob

**Comment by gekorob** [comment]
Hi @ahrechushkin I'm looking at this issue.
Reconfiguring the VM reducing only the RAM amount is working and the message you are referring to is related to an un-handled event (you can find it also in evm.log). 
But the operation it self is working, at least alone. 
I'll dig deeper to see if can be related to both decreasing CPUS and RAM

**Comment by ahrechushkin** [comment]
@gekorob when i try reduce only memory without CPU i have the same problem

**Comment by gekorob** [comment]
@ahrechushkin that's strange. Reducing only the RAM should work but requires the VM to be restarted cause, at least in my case, it sets next_run to true. Increasing the RAM only instead applies to the VM without restarting.
I'm testing using the upstream connecting to a RHV 4.3.6 and reconfiguring a VM rhel 7.7 with guest agent.
The reason why reducing memory and cpu at the same time is not working is probably because settings are applied with sequential updates and the options that requires a "next_run" can be merged only if the update has the next_run set to true.
