### ISSUE TITLE
Network/Networks screen is broken after upgrading to morphy

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/manageiq-providers-ovirt#578]
![image](https://user-images.githubusercontent.com/651659/142481364-1ed9d8a4-1bb6-44ad-a2e1-99fc52e0f4e3.png)

It looks like this was broken by https://github.com/ManageIQ/manageiq-providers-ovirt/pull/569

**Comment by agrare** [comment]
The issue here is that `CloudNetwork.class_by_ems` is simply doing `ext_management_system.class::CloudNetwork` which in this case is resolving to `ManageIQ::Providers::Redhat::NetworkManager::CloudNetwork`

These subclasses existed prior to https://github.com/ManageIQ/manageiq-providers-ovirt/pull/569 but no records of this type were ever created due to https://github.com/ManageIQ/manageiq-providers-openstack/pull/714

In order for `CloudNetwork.class_by_ems` to work properly on morphy we'll need to alias the ovirt network manager to the openstack one.

**Comment by bdunne** [comment]
These all have the same problem:
https://github.com/ManageIQ/manageiq/blob/morphy/app/models/cloud_network.rb#L51
https://github.com/ManageIQ/manageiq/blob/morphy/app/models/cloud_subnet.rb#L55
https://github.com/ManageIQ/manageiq/blob/morphy/app/models/network_router.rb#L53
https://github.com/ManageIQ/manageiq/blob/morphy/app/models/security_group.rb#L40
https://github.com/ManageIQ/manageiq/blob/morphy/app/models/floating_ip.rb#L26

**Comment by Fryguy** [comment]
Merged https://github.com/ManageIQ/manageiq-providers-ovirt/pull/579 - is this fixed then?

**Comment by agrare** [comment]
Yeah, weird I had `Fixes #579` in the description

My guess because it wasn't merged to master github didn't consider it "fixed"
